services:
  - type: web
    name: resource-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    disk:
      name: resource-data
      mountPath: /app/storage
      sizeGB: 1
    envVars:
      - key: EXECUTION_MODE
        value: solana
      - key: DATA_DIR
        value: /app/storage/data
      - key: SCHEDULER_ENABLED
        value: "false"
      - key: SCHEDULER_POLL_MS
        value: "30000"
      - key: FRONTEND_ORIGIN
        sync: false
      - key: OPERATOR_API_KEY
        sync: false
      - key: PUBLIC_DEMO_ENABLED
        value: "true"
      - key: SOLANA_CLUSTER
        value: devnet
      - key: SOLANA_RPC_URL
        value: https://api.devnet.solana.com
      - key: SOLANA_RPC_SUBSCRIPTIONS_URL
        value: wss://api.devnet.solana.com
      - key: SOLANA_KEYPAIR_PATH
        value: /etc/secrets/solana-keypair.json
      - key: SOLANA_TOKEN_MINT
        value: FCv4FDXqEcLDXn6F55TcPst9DZY3uo6YDeVUxN6SgnLw
      - key: SOLANA_TOKEN_SYMBOL
        value: tUSDC
      - key: SOLANA_TOKEN_DECIMALS
        value: "6"
      - key: SOLANA_REGISTRY_PROGRAM_ID
        value: G3sta1z39YXTX5dopAXtuv6kqBTQGoN9G85DMW3WVvm4
      - key: RESOURCE_PROVIDER_SENTINEL_SOLANA_ADDRESS
        value: 5UXeGPPJPx65T81PJitht2YscnQFNuy3vyPQUqAGrbE4
      - key: RESOURCE_PROVIDER_ATLAS_SOLANA_ADDRESS
        value: 2LK5M8TcbUFazXHSzCFxKd3u7UG9171zCk62AJF1jsav
